default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/joynuss_staffing_dev_db

test:
  <<: *default
  database: db/joynuss_staffing_test_db

production:
  url: <%= ENV["DATABASE_URL"] %>
